pull_request_rules:
  - name: merge-when-labeled
    conditions:
      - base=main
      - label=zz-merge
    actions:
      merge:
        method: merge
        commit_message_template: |
          plain merge with no governance marker
